### ISSUE TITLE
Add  macOs platform in 'matrix strategy' for CI test 

### ISSUE THREAD

**Issue by outscale-toa** [outscale/packer-plugin-outscale#157]
```
....
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        version: [12, 14, 16]
    runs-on: ${{ matrix.os }}
    steps:
....
```
